### ISSUE TITLE
sparse status internal error [mkl_sparse_qr_reorder]

### ISSUE THREAD

**Issue by jvandeweg** [flatironinstitute/sparse_dot#21]
I came across this library in my search for a (much) faster option for solving sparse matrix equation on windows. The installation worked flawlessly, however I have trouble getting the qr solver to work. 
I have a large complex matrix sEmA, 160k x 160k (roughly 2.4 million non-zeros), that needs to be solved for Ax=B, with B being 160k x 2 (roughly 29k non-zeros). When I try to solve the problem using

`U = sparse_qr_solve_mkl(sEmA, B.todense(), cast=True)`

I get the following output/errors:

> Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
MKL Number of Threads: 8
MKL linked: C:\ProgramData\Miniconda3\envs\python39\Library\bin\mkl_rt.1.dll
MKL interface <class 'numpy.int32'> | <class 'ctypes.c_long'>
Set int32 interface with env MKL_INTERFACE_LAYER=LP64
Set int64 interface with env MKL_INTERFACE_LAYER=ILP64
Recasting matrix data type float64 to complex128
mkl_sparse_z_create_csc returned 0 (SPARSE_STATUS_SUCCESS)
mkl_sparse_convert_csr returned 0 (SPARSE_STATUS_SUCCESS)
Traceback (most recent call last):
  File "C:\Projects\2020067\Deliverable 3.2\Frequency Analysis\02bode_direct.py", line 79, in <module>
    res.append(calcSaveBode(f))
  File "C:\Projects\2020067\Deliverable 3.2\Frequency Analysis\02bode_direct.py", line 55, in calcSaveBode
    U = sdm.sparse_qr_solve_mkl(sEmA, B.todense(), cast=True)
  File "C:\ProgramData\Miniconda3\envs\python39\lib\site-packages\sparse_dot_mkl\sparse_dot.py", line 140, in sparse_qr_solve_mkl
    return _qrs(matrix_a, matrix_b, cast=cast)
  File "C:\ProgramData\Miniconda3\envs\python39\lib\site-packages\sparse_dot_mkl\_sparse_qr_solver.py", line 89, in sparse_qr_solver
    x_arr = _sparse_qr(matrix_a, matrix_b if matrix_b.ndim == 2 else matrix_b.reshape(-1, 1))
  File "C:\ProgramData\Miniconda3\envs\python39\lib\site-packages\sparse_dot_mkl\_sparse_qr_solver.py", line 34, in _sparse_qr
    _check_return_value(ret_val_r, "mkl_sparse_qr_reorder")
  File "C:\ProgramData\Miniconda3\envs\python39\lib\site-packages\sparse_dot_mkl\_mkl_interface\_common.py", line 492, in _check_return_value
    raise ValueError(err_msg)
ValueError: mkl_sparse_qr_reorder returned 5 (SPARSE_STATUS_INTERNAL_ERROR)

Whatever I have tried did not resolve my problem.

**Comment by asistradition** [comment]
This should have a clearer error message, but the MKL QR solver doesn't support complex data, only real floats

**Comment by jvandeweg** [comment]
That explains a lot! Well then my search for efficiency continues on.

**Comment by asistradition** [comment]
I added an explicit error message anyway to make it clear
