### ISSUE TITLE
Import fails when using SciPy 1.14

### ISSUE THREAD

**Issue by hrittich** [flatironinstitute/sparse_dot#25]
Running the following code when SciPy 1.14 is installed fails.

    from sparse_dot_mkl import dot_product_mkl

The corresponding output is as follow.

    Traceback (most recent call last):
      File "/home/hrittich/workspace/sparse-dot-mkl-bug-mwe/import-fail.py", line 1, in <module>
        from sparse_dot_mkl import dot_product_mkl
      File "/home/hrittich/workspace/sparse-dot-mkl-bug-mwe/.venv/lib/python3.11/site-packages/sparse_dot_mkl/__init__.py", line 4, in <module>
        from sparse_dot_mkl.sparse_dot import (
      File "/home/hrittich/workspace/sparse-dot-mkl-bug-mwe/.venv/lib/python3.11/site-packages/sparse_dot_mkl/sparse_dot.py", line 1, in <module>
        from sparse_dot_mkl._sparse_sparse import _sparse_dot_sparse as _sds
      File "/home/hrittich/workspace/sparse-dot-mkl-bug-mwe/.venv/lib/python3.11/site-packages/sparse_dot_mkl/_sparse_sparse.py", line 1, in <module>
        from sparse_dot_mkl._mkl_interface import (
      File "/home/hrittich/workspace/sparse-dot-mkl-bug-mwe/.venv/lib/python3.11/site-packages/sparse_dot_mkl/_mkl_interface/__init__.py", line 140, in <module>
        _empirical_set_dtype()
      File "/home/hrittich/workspace/sparse-dot-mkl-bug-mwe/.venv/lib/python3.11/site-packages/sparse_dot_mkl/_mkl_interface/__init__.py", line 104, in _empirical_set_dtype
        _validate_dtype()
      File "/home/hrittich/workspace/sparse-dot-mkl-bug-mwe/.venv/lib/python3.11/site-packages/sparse_dot_mkl/_mkl_interface/__init__.py", line 72, in _validate_dtype
        test_comparison = test_array.A
                          ^^^^^^^^^^^^
    AttributeError: 'csc_matrix' object has no attribute 'A'

I am assuming that the `A` attribute had been deprecated in SciPy.

**Comment by asistradition** [comment]
Yeah looks like a bunch of sparse attributes (including `.A`) were deprecated in 1.14

Fixed in 2cb7753 and released as 0.9.4

**Comment by hrittich** [comment]
> Fixed in [2cb7753](https://github.com/flatironinstitute/sparse_dot/commit/2cb7753ee4a6df541c7b4bc704ba8f0d5eab6c0d) and released as 0.9.4

Thank you! 👍
